[project]
name = "mcp-collection"
version = "1.0.0"
description = "MCP collection with integrated supergateway"
requires-python = ">=3.13"
dependencies = [
    "mcp-server-fetch==2025.4.7",
    "mcp-server-qdrant==0.7.1",
]
